name: Dim CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:  
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake (C++20)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDIM_BUILD_TEST=ON -DDIM_CXX_VERSION=20

    - name: Build (C++20)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test (C++20)
      working-directory: ${{github.workspace}}/build
      run: ./test/dimTest

    - name: Configure CMake  (C++17)
      run: 
         cmake -B ${{github.workspace}}/build.17 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDIM_BUILD_TEST=ON -DDIM_CXX_VERSION=17

    - name: Build (C++17)
      run: cmake --build ${{github.workspace}}/build.17 --config ${{env.BUILD_TYPE}}

    - name: Test (C++17)
      working-directory: ${{github.workspace}}/build.17
      run: ./test/dimTest

    - name: Configure CMake  (C++14)
      run: 
         cmake -B ${{github.workspace}}/build.14 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDIM_BUILD_TEST=ON -DDIM_CXX_VERSION=14

    - name: Build (C++14)
      run: cmake --build ${{github.workspace}}/build.14 --config ${{env.BUILD_TYPE}}

    - name: Test (C++14)
      working-directory: ${{github.workspace}}/build.14
      run: ./test/dimTest

    - name: Configure CMake  (C++11)
      run: 
         cmake -B ${{github.workspace}}/build.11 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDIM_BUILD_TEST=ON -DDIM_CXX_VERSION=11

    - name: Build (C++11)
      run: cmake --build ${{github.workspace}}/build.11 --config ${{env.BUILD_TYPE}}

    - name: Test (C++11)
      working-directory: ${{github.workspace}}/build.11
      run: ./test/dimTest

